linters:
  disable-all: true
  enable:
    - gofmt
    - errcheck
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

run:
  skip-files:
    # These were code-generated, and cannot be changed without breaking RPC compatibility.
    - lambda/messages/*.go

    # FIXME
    # events/codedeploy.go:16:2: SA9004: only the first constant in this group has an explicit type (staticcheck)
    #	CodeDeployDeploymentStateFailure CodeDeployDeploymentState = "FAILURE"
    #	^
    - events/codedeploy.go
